# Generated by Django 2.1.4 on 2020-04-21 08:15

import accounts.account_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200421_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, validators=[accounts.account_validation.validator.phone]),
        ),
    ]
